services:
  - type: web
    name: papeleria-db-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseProvider
        value: Postgres
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: JwtSettings__Secret
        generateValue: true
